FROM python:3.8 as ptportal-web-base

RUN apt-get update && apt-get install -y \
  p7zip-full \
  nano \
  npm \
  zip

ADD docker/dev/requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY node /code/node
RUN cd /code && npm install -D node/dependencies/tailwindcss-3 --legacy-peer-deps \
  && npm install -D node/dependencies/components-vue3 --legacy-peer-deps


FROM ptportal-web-base

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /code/pentestportal/media
WORKDIR /code
