---

services:
  db:
    container_name: prod-db-1
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: prod-web-1
    build:
      context: .
      dockerfile: docker/prod/Dockerfile.web
    command: gunicorn pentestportal.wsgi:application --bind 0.0.0.0:8080
    env_file: docker/prod/env.txt
    depends_on:
      - db
    volumes:
      # - web_volume:/code # uncomment this if you do not want
      # to mount the directory and edit files (and comment out the .:/code)
      - .:/code
  nginx:
    container_name: prod-nginx-1
    build:
      context: docker/prod/nginx
      dockerfile: Dockerfile.nginx
    restart: always
    volumes:
      - .:/code
    ports:
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  web_volume:

networks:
  default:
    name: ptportal
