---

services:
  db:
    container_name: dev-db-1
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    container_name: dev-web-1
    build:
      context: .
      dockerfile: docker/dev/Dockerfile.web
    command: docker/dev/wait-for-it.sh -h db -p 5432 -t 30 -- python manage.py runserver 0.0.0.0:8080
    env_file: docker/dev/env.txt
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - .:/code

volumes:
  postgres_data:

networks:
  default:
    name: ptportal
